### ISSUE TITLE
How does the first time point decided in getTimeRNA?

### ISSUE THREAD

**Issue by scjlee** [tzhu-bio/cisDynet#11]
Hi,

I got the error: `Error in column_idx:ncol(df) : NA/NaN argument` when running `getTimeRNA` . As the code snippet below, it seems that the issue is due to no Z-score are greater than 1.9 in the first Interpolated gene. 

https://github.com/tzhu-bio/cisDynet/blob/c5b99d37f12e7d2d8ef1fde766e37efd639f6904/R/TimeSeries.R#L119-L124

I can circumvent the error by modifying the function to use a different gene or different Z-score threshold, but I'm not sure it is a correct way. I wonder how are the filtering criteria (first gene and > 1.9) decided and is there any way to avoid this issue.

Thanks

**Comment by tzhu-bio** [comment]
Thank you for raising this question. After sorting the matrix, there are usually blank columns at the end. The reason for filtering is to avoid blank columns in the visualisation results. The reason for choosing 1.9 is because the Z-score I made the restriction to be in the range from -2 to 2. From your data, it looks like the RNA's have a small range of differences after Z-score conversion? You could try changing the 1.9 here to 0.9*max(Z-score). Like what I'm using here is 1.9 relative to max 2. This first time point is actually determined by the activity of ATAC, based on the Peak2gene results.

**Comment by cjlee13** [comment]
Thanks for your response! It fixes my problem.
